version: "3.9"
services:
  node_server:
    container_name: node_server
    build: .
    depends_on:
      - "postgres_db"
    ports:
      - "8080:8080"
    networks:
      - "cube"
    env_file:
      - "./server.env"
  postgres_db:
    container_name: postgres_db
    image: "postgres:latest"
    restart: always
    expose:
      - "5432"
    networks:
      - "cube"
    env_file:
      - "./postgres.env"

networks:
  cube:
